service: serverless-mongodb
provider:
  name: aws
  runtime: nodejs12.x # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-east-1

functions: # add 4 functions for CRUD
  create:
    handler: src/handler.create # point to exported create function in handler.ts
    events:
      - http:
          path: cards # path will be domain.name.com/dev/notes
          method: post
          cors: true
  getOne:
    handler: src/handler.getOne
    events:
      - http:
          path: cards/{id} # path will be domain.name.com/dev/notes/1
          method: get
          cors: true
  getAll:
    handler: src/handler.getAll # path will be domain.name.com/dev/notes
    events:
      - http:
          path: cards
          method: get
          cors: true
  update:
    handler: src/handler.update # path will be domain.name.com/dev/notes/1
    events:
      - http:
          path: cards/{id}
          method: put
          cors: true
  delete:
    handler: src/handler.deleteNote
    events:
      - http:
          path: cards/{id} # path will be domain.name.com/dev/notes/1
          method: delete
          cors: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline # adding the plugin to be able to run the offline emulation

